controller_manager:
  ros__parameters:
    update_rate: 100  
    use_sim_time: true


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


    left_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    left_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    left_gripper_controller:
      type: position_controllers/JointGroupPositionController


    right_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    right_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    right_gripper_controller:
      type: position_controllers/JointGroupPositionController


left_velocity_controller:
  ros__parameters:
    joints:
      - left_joint_a1
      - left_joint_a2
      - left_joint_a3
      - left_joint_a4
      - left_joint_a5
      - left_joint_a6
      - left_joint_a7
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity

left_joint_trajectory_controller:
  ros__parameters:
    joints:
      - left_joint_a1
      - left_joint_a2
      - left_joint_a3
      - left_joint_a4
      - left_joint_a5
      - left_joint_a6
      - left_joint_a7
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity


left_gripper_controller:
  ros__parameters:
    joints:
      - left_finger_left_joint
      - left_finger_right_joint
    interface_name: position


right_velocity_controller:
  ros__parameters:
    joints:
      - right_joint_a1
      - right_joint_a2
      - right_joint_a3
      - right_joint_a4
      - right_joint_a5
      - right_joint_a6
      - right_joint_a7
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity

right_joint_trajectory_controller:
  ros__parameters:
    joints:
      - right_joint_a1
      - right_joint_a2
      - right_joint_a3
      - right_joint_a4
      - right_joint_a5
      - right_joint_a6
      - right_joint_a7
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity


right_gripper_controller:
  ros__parameters:
    joints:
      - right_finger_left_joint
      - right_finger_right_joint
    interface_name: position
